In [51]:
class MeraLR:
    
    def __init__(self):
        self.m = None
        self.b = None
    
    def fit(self, X_train , y_train):
        num = 0
        den = 0
        for i in range(X_train.shape[0]):
            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))
            
        
        
        self.m = num/den
        self.b = (y_train.mean() - (self.m)*(X_train.mean()))
        
    
    def predict(self, X_test):
        
        return (self.m*X_test + self.b)

In [52]:
mlr = MeraLR()

In [53]:
mlr.fit(X_train, y_train)

In [59]:
print(mlr.predict(X_test[0]))

31.72042453960878


In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('placements.txt')

In [3]:
df.head()

cgpa  placement_exam_marks  placed
0  7.19                  26.0       1
1  7.46                  38.0       1
2  7.54                  40.0       1
3  6.42                   8.0       1
4  7.23                  17.0       0

In [4]:
X = df.iloc[:, 0].values
y = df.iloc[:, 1].values

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2)

In [7]:
X_train

array([7.57, 5.52, 6.75, 7.71, 5.77, 6.9 , 6.97, 6.4 , 7.12, 7.82, 5.74,
       6.55, 7.46, 7.78, 7.29, 7.  , 6.93, 6.98, 7.34, 7.42, 6.51, 6.59,
       6.01, 7.07, 6.1 , 6.74, 7.61, 6.93, 6.96, 6.87, 7.31, 7.49, 7.24,
       7.08, 6.1 , 6.76, 5.97, 7.11, 6.84, 5.92, 7.2 , 6.22, 6.34, 6.64,
       7.06, 7.21, 7.96, 7.03, 7.22, 7.34, 6.87, 7.32, 7.14, 7.8 , 6.67,
       6.49, 6.31, 7.2 , 6.38, 6.87, 6.94, 7.  , 7.95, 7.46, 6.82, 7.73,
       6.85, 7.  , 7.07, 7.31, 7.37, 5.74, 7.47, 7.52, 7.23, 7.56, 8.29,
       7.16, 7.01, 6.95, 7.31, 6.74, 6.51, 7.41, 7.97, 7.  , 6.22, 8.03,
       6.04, 5.68, 6.9 , 6.57, 6.26, 7.18, 7.03, 6.5 , 6.37, 6.18, 7.49,
       6.81, 7.61, 6.67, 7.16, 6.74, 6.77, 6.48, 6.24, 6.52, 7.33, 7.31,
       7.17, 6.63, 8.21, 7.18, 7.9 , 7.54, 7.23, 6.3 , 7.07, 6.58, 7.19,
       7.98, 6.59, 6.17, 5.94, 6.21, 6.86, 7.3 , 6.52, 6.38, 6.9 , 7.2 ,
       6.87, 7.12, 7.17, 6.28, 7.46, 5.91, 6.63, 7.65, 6.73, 7.31, 5.48,
       6.12, 6.24, 8.04, 7.28, 5.83, 6.55, 7.67, 7.

In [8]:
y_train

array([ 26.,  62.,  24.,  25.,  22.,  20.,  87.,  24.,  34.,  35.,  43.,
        35.,  31.,  56.,  23.,   9.,  10.,  34.,  41.,   6.,  27.,  42.,
         9.,  25.,  37.,  60.,  22.,  27.,  48.,  22.,  61.,  58.,  34.,
        22.,  20.,  54.,  26.,  13.,  34.,  55.,  52.,  46.,  39.,  20.,
        22.,  21.,  37.,  19.,  18.,  32.,  20.,   9.,  18.,  15.,  10.,
        21.,  19.,  70.,  25.,  46.,  20.,  13.,  12.,  16.,  16.,  30.,
        21.,   9.,  81.,  33.,  35.,  76.,  19.,  35.,  17.,   6.,  44.,
        21.,   5.,  43.,  21.,   2.,  48.,  30.,  52.,  39.,  40.,  39.,
        37.,  26.,  44.,  11.,  13.,   8.,  33.,  16.,  63.,  36.,  22.,
        39.,  15.,  32.,  37.,   8.,  42.,  33.,  39.,  22.,  36.,  24.,
        26.,  23.,  56.,  50.,  19.,  40.,  54.,  23.,  18.,  16.,  20.,
         6.,  36.,  39.,  10.,  74.,  41.,  42.,  10.,  15.,  17.,  47.,
        42.,  33.,  49.,  18.,  71.,  50.,  39.,  12.,  22.,  86.,  18.,
        17.,  38.,  26.,  14.,  68.,  62.,  23.,   

In [9]:
X_train.shape[0]

800

In [39]:
y_test

array([ 9., 25., 97., 64., 23.,  9., 17., 58., 13., 56., 53., 39., 44.,
       19., 21., 61., 12., 69., 45., 20., 19., 18., 35.,  6., 27., 43.,
       60., 38., 23., 34., 27., 11., 47.,  9.,  9., 22., 47., 35., 18.,
       45., 23., 37.,  9., 17., 16., 79., 25., 17., 17.,  7., 21., 15.,
       14., 16., 60., 16., 16., 17., 34.,  2., 76., 52., 26., 47., 31.,
       30., 12., 79., 46., 38., 40., 21., 45., 17., 36., 14., 19., 33.,
       14., 28., 30., 34., 59., 24., 20., 33., 34., 55., 25., 28., 45.,
       55., 28., 29., 49., 50., 17., 42., 27., 22., 48.,  6., 48., 10.,
       25., 52., 26., 21., 63., 25., 55., 16., 39., 38., 63., 14., 14.,
       15., 87., 22., 66., 49., 38., 34., 65., 57., 17., 26., 11., 21.,
       43., 23., 60., 58., 43., 17., 18., 29., 50., 10., 32., 16., 17.,
       31., 55., 48., 43., 13., 63., 27., 41., 25., 63., 10., 36., 65.,
       14.,  3., 21., 65., 20., 35., 37., 51., 62., 35., 41., 13., 56.,
       18.,  8., 23., 62., 37., 37., 38., 18., 21., 10., 34., 14

In [40]:
X_test

array([8.51, 7.93, 6.99, 6.02, 6.85, 7.57, 6.34, 6.29, 6.4 , 6.23, 5.69,
       8.  , 7.75, 6.54, 7.51, 6.36, 6.52, 6.5 , 6.5 , 6.13, 6.62, 8.04,
       6.4 , 7.52, 6.75, 6.42, 6.25, 6.67, 7.46, 6.65, 6.19, 6.15, 6.99,
       7.02, 6.71, 6.75, 6.69, 7.13, 6.75, 7.38, 6.81, 8.12, 6.1 , 7.46,
       6.6 , 5.7 , 8.48, 7.22, 6.24, 6.78, 7.1 , 6.84, 6.66, 6.68, 6.56,
       6.89, 7.48, 6.33, 6.29, 8.04, 6.87, 7.37, 6.48, 7.52, 7.3 , 6.58,
       6.51, 7.37, 7.45, 6.77, 8.49, 7.07, 6.46, 6.06, 7.7 , 6.41, 7.06,
       7.19, 7.12, 7.85, 7.  , 7.77, 6.91, 6.92, 8.14, 6.32, 7.56, 7.02,
       7.43, 6.27, 6.4 , 6.62, 6.46, 6.79, 6.82, 5.74, 7.41, 7.72, 7.48,
       7.53, 6.93, 6.12, 7.52, 7.28, 6.47, 6.22, 6.67, 7.26, 6.71, 7.24,
       7.26, 7.27, 7.12, 7.48, 7.9 , 6.31, 7.32, 6.7 , 6.05, 6.89, 6.04,
       7.65, 6.42, 7.23, 6.  , 6.23, 7.19, 8.27, 6.97, 6.46, 5.27, 5.99,
       6.14, 5.51, 7.6 , 6.56, 7.19, 6.3 , 5.56, 7.07, 7.33, 6.71, 6.98,
       7.31, 7.02, 7.55, 6.92, 7.61, 6.44, 7.2 , 8.

In [43]:
lr.predict(6.39)

32.28227657534983

In [44]:
from sklearn.linear_model import LinearRegression

In [45]:
lr = LinearRegression()

In [48]:
lr.fit(X_train.reshape(-1,1), y_train.reshape(-1,1))

LinearRegression()

In [60]:
lr.predict(X_test[0].reshape(-1,1))

array([[31.72042454]])